package Server;

public enum Endpoint {
    GET_TASK,
    GET_SUBTASK,
    GET_EPIC,
    GET_TASK_BY_ID,
    GET_SUBTASK_BY_ID,
    GET_EPIC_BY_ID,
    GET_SUBTASKS_FROM_EPIC,
    GET_USER_HISTORY,
    GET_PRIORITIZED_TASKS,
    POST_ADD_OR_UPDATE_TASK,
    POST_ADD_OR_UPDATE_SUBTASK,
    POST_ADD_OR_UPDATE_EPIC,
    DELETE_TASKS,
    DELETE_SUBTASKS,
    DELETE_EPICS,
    DELETE_TASK_BY_ID,
    DELETE_SUBTASK_BY_ID,
    DELETE_EPIC_BY_ID,
    NULL
}




